<?php

// Require the autoload file generated by Composer
    require_once 'vendor/autoload.php';

// Instantiate Fat-Free framework (F3)
    $f3 = \Base::instance();

// Define a default route for the home page
    $f3->route('GET /', function() {
        $view = new \Template();
        echo $view->render('views/home.html');
    });

// Define routes for personal, experience, and mail forms
    $f3->route('GET /personal', function() {
        $view = new \Template();
        echo $view->render('personal.html');
    });

    $f3->route('GET /experience', function() {
        $view = new \Template();
        echo $view->render('views/experience.html');
    });

    $f3->route('GET /mail', function() {
        $view = new \Template();
        echo $view->render('views/mail.html');
    });

// Define a route to display the summary after form submission
    $f3->route('GET /summary', function() {
        $view = new \Template();
        echo $view->render('views/summary.html');
    });

// Run Fat-Free
    $f3->run();
